env: macad

env_args:
  seed: 10
  episode_limit: 500

save_model: True
save_model_interval: 1500
batch_size: 4
buffer_cpu_only: True
test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
