env: macad

env_args:
  seed: 10
  episode_limit: 300

batch_size: 8
buffer_cpu_only: False
test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
